import { CodeLine, CodeLanguage } from '../types';

export type DSType = 'array' | 'pq';

export const codeTemplates: Record<CodeLanguage, Record<DSType, { title: string; lines: CodeLine[] }>> = {
  'pseudo-c': {
    'array': {
      title: 'Tựa C - Mảng Tuyến Tính d[v] - O(V²)',
      lines: [
        { key: 'init', text: 'Dijkstra(graph, n, src) // graph là ma trận kề hoặc danh sách kề, n là số đỉnh', indent: 0 },
        { key: 'init', text: '{', indent: 0 },
        { key: 'init', text: '    for (i = 0; i < n; i++)', indent: 0 },
        { key: 'init', text: '    {', indent: 1 },
        { key: 'init', text: '        dist[i] = ∞;', indent: 2 },
        { key: 'init', text: '        prev[i] = -1;   // dùng -1 thay cho None', indent: 2 },
        { key: 'init', text: '        open[i] = 1;    // 1 nghĩa là đỉnh i còn trong tập open', indent: 2 },
        { key: 'init', text: '    }', indent: 1 },
        { key: 'init', text: '    dist[src] = 0;', indent: 1 },
        { key: 'init', text: '', indent: 0 },
        { key: 'loop_start', text: '    while (còn tồn tại u sao cho open[u] == 1)', indent: 1 },
        { key: 'loop_start', text: '    {', indent: 1 },
        { key: 'extract_min', text: '        // Tìm u có dist[u] nhỏ nhất trong số các đỉnh còn trong open', indent: 2 },
        { key: 'extract_min', text: '        min = ∞;', indent: 2 },
        { key: 'extract_min', text: '        for (i = 0; i < n; i++)', indent: 2 },
        { key: 'extract_min', text: '        {', indent: 2 },
        { key: 'extract_min', text: '            if (open[i] == 1 && dist[i] < min)', indent: 3 },
        { key: 'extract_min', text: '            {', indent: 3 },
        { key: 'extract_min', text: '                min = dist[i];', indent: 4 },
        { key: 'extract_min', text: '                u = i;', indent: 4 },
        { key: 'extract_min', text: '            }', indent: 3 },
        { key: 'extract_min', text: '        }', indent: 2 },
        { key: 'extract_min', text: '', indent: 0 },
        { key: 'mark_visited', text: '        open[u] = 0; // loại u khỏi open', indent: 2 },
        { key: 'mark_visited', text: '', indent: 0 },
        { key: 'neighbor_loop', text: '        // Cập nhật khoảng cách cho các đỉnh kề với u', indent: 2 },
        { key: 'neighbor_loop', text: '        for (v = 0; v < n; v++)', indent: 2 },
        { key: 'neighbor_loop', text: '        {', indent: 2 },
        { key: 'relaxation_check', text: '            if (graph[u][v] > 0) // nếu có cạnh từ u đến v', indent: 3 },
        { key: 'relaxation_check', text: '            {', indent: 3 },
        { key: 'relaxation_check', text: '                w = graph[u][v];', indent: 4 },
        { key: 'relaxation_check', text: '                if (dist[u] + w < dist[v])', indent: 4 },
        { key: 'relaxation_check', text: '                {', indent: 4 },
        { key: 'relaxation_action', text: '                    dist[v] = dist[u] + w;', indent: 5 },
        { key: 'relaxation_action', text: '                    prev[v] = u;', indent: 5 },
        { key: 'relaxation_action', text: '                }', indent: 4 },
        { key: 'relaxation_check', text: '            }', indent: 3 },
        { key: 'neighbor_loop', text: '        }', indent: 2 },
        { key: 'loop_start', text: '    }', indent: 1 },
        { key: 'done', text: '    return ; // dist và prev được lưu toàn cục hoặc in sau đó', indent: 1 },
        { key: 'done', text: '}', indent: 0 },
      ]
    },
    'pq': {
      title: 'Tựa C - Hàng Đợi Ưu Tiên (Min-Heap) - O((V+E) log V)',
      lines: [
        { key: 'init', text: 'Dijkstra_Heap(graph, n, src)', indent: 0 },
        { key: 'init', text: '{', indent: 0 },
        { key: 'init', text: '    for (i = 0; i < n; i++)', indent: 0 },
        { key: 'init', text: '    {', indent: 1 },
        { key: 'init', text: '        dist[i] = ∞;', indent: 2 },
        { key: 'init', text: '        prev[i] = -1;', indent: 2 },
        { key: 'init', text: '    }', indent: 1 },
        { key: 'init', text: '    dist[src] = 0;', indent: 1 },
        { key: 'init', text: '    pq_init(&Q);', indent: 1 },
        { key: 'init', text: '    pq_insert(&Q, src, 0); // Đưa nguồn vào hàng đợi', indent: 1 },
        { key: 'init', text: '', indent: 0 },
        { key: 'loop_start', text: '    while (!pq_is_empty(&Q))', indent: 1 },
        { key: 'loop_start', text: '    {', indent: 1 },
        { key: 'extract_min', text: '        u = pq_extract_min(&Q); // Lấy u có khoảng cách nhỏ nhất, O(log V)', indent: 2 },
        { key: 'extract_min', text: '        if (dist[u] == ∞) break;', indent: 2 },
        { key: 'extract_min', text: '', indent: 0 },
        { key: 'neighbor_loop', text: '        for (v = 0; v < n; v++)', indent: 2 },
        { key: 'neighbor_loop', text: '        {', indent: 2 },
        { key: 'relaxation_check', text: '            if (graph[u][v] > 0)', indent: 3 },
        { key: 'relaxation_check', text: '            {', indent: 3 },
        { key: 'relaxation_check', text: '                w = graph[u][v];', indent: 4 },
        { key: 'relaxation_check', text: '                if (dist[u] + w < dist[v])', indent: 4 },
        { key: 'relaxation_check', text: '                {', indent: 4 },
        { key: 'relaxation_action', text: '                    dist[v] = dist[u] + w;', indent: 5 },
        { key: 'relaxation_action', text: '                    prev[v] = u;', indent: 5 },
        { key: 'relaxation_action', text: '                    pq_decrease_key_or_insert(&Q, v, dist[v]); // Cập nhật Heap O(log V)', indent: 5 },
        { key: 'relaxation_action', text: '                }', indent: 4 },
        { key: 'relaxation_check', text: '            }', indent: 3 },
        { key: 'neighbor_loop', text: '        }', indent: 2 },
        { key: 'loop_start', text: '    }', indent: 1 },
        { key: 'done', text: '}', indent: 0 },
      ]
    }
  },
  'c': {
    'array': {
      title: 'C - Mảng Tuyến Tính - O(V²)',
      lines: [
        { key: 'init', text: '#define INF 999999', indent: 0 },
        { key: 'init', text: '', indent: 0 },
        { key: 'init', text: 'int still_open()', indent: 0 },
        { key: 'init', text: '{', indent: 0 },
        { key: 'init', text: '    for (int i = 0; i < n; i++) {', indent: 1 },
        { key: 'init', text: '        if (open[i] == 1) return 1;', indent: 2 },
        { key: 'init', text: '    }', indent: 1 },
        { key: 'init', text: '    return 0;', indent: 1 },
        { key: 'init', text: '}', indent: 0 },
        { key: 'init', text: '', indent: 0 },
        { key: 'init', text: 'void Dijkstra(int graph[100][100], int n, int src)', indent: 0 },
        { key: 'init', text: '{', indent: 0 },
        { key: 'init', text: '    for (i = 0; i < n; i++)', indent: 0 },
        { key: 'init', text: '    {', indent: 1 },
        { key: 'init', text: '        dist[i] = INF;', indent: 2 },
        { key: 'init', text: '        prev[i] = -1;', indent: 2 },
        { key: 'init', text: '        open[i] = 1;', indent: 2 },
        { key: 'init', text: '    }', indent: 1 },
        { key: 'init', text: '    dist[src] = 0;', indent: 1 },
        { key: 'init', text: '', indent: 0 },
        { key: 'loop_start', text: '    while (still_open())', indent: 1 },
        { key: 'loop_start', text: '    {', indent: 1 },
        { key: 'extract_min', text: '        min = INF;', indent: 2 },
        { key: 'extract_min', text: '        for (i = 0; i < n; i++)', indent: 2 },
        { key: 'extract_min', text: '        {', indent: 2 },
        { key: 'extract_min', text: '            if (open[i] == 1 && dist[i] < min)', indent: 3 },
        { key: 'extract_min', text: '            {', indent: 3 },
        { key: 'extract_min', text: '                min = dist[i];', indent: 4 },
        { key: 'extract_min', text: '                u = i;', indent: 4 },
        { key: 'extract_min', text: '            }', indent: 3 },
        { key: 'extract_min', text: '        }', indent: 2 },
        { key: 'extract_min', text: '', indent: 0 },
        { key: 'mark_visited', text: '        open[u] = 0; // Thăng vị chốt đỉnh u', indent: 2 },
        { key: 'mark_visited', text: '', indent: 0 },
        { key: 'neighbor_loop', text: '        for (v = 0; v < n; v++)', indent: 2 },
        { key: 'neighbor_loop', text: '        {', indent: 2 },
        { key: 'relaxation_check', text: '            if (graph[u][v] > 0)', indent: 3 },
        { key: 'relaxation_check', text: '            {', indent: 3 },
        { key: 'relaxation_check', text: '                w = graph[u][v];', indent: 4 },
        { key: 'relaxation_check', text: '                if (dist[u] + w < dist[v])', indent: 4 },
        { key: 'relaxation_check', text: '                {', indent: 4 },
        { key: 'relaxation_action', text: '                    dist[v] = dist[u] + w;', indent: 5 },
        { key: 'relaxation_action', text: '                    prev[v] = u;', indent: 5 },
        { key: 'relaxation_action', text: '                }', indent: 4 },
        { key: 'relaxation_check', text: '            }', indent: 3 },
        { key: 'neighbor_loop', text: '        }', indent: 2 },
        { key: 'loop_start', text: '    }', indent: 1 },
        { key: 'done', text: '}', indent: 0 },
      ]
    },
    'pq': {
      title: 'C - Hàng Đợi Ưu Tiên (Min-Heap Struct) - O((V+E) log V)',
      lines: [
        { key: 'init', text: '#define INF 999999', indent: 0 },
        { key: 'init', text: 'typedef struct { int node; int dist; } HeapNode;', indent: 0 },
        { key: 'init', text: 'typedef struct { HeapNode data[100]; int size; } MinHeap;', indent: 0 },
        { key: 'init', text: '', indent: 0 },
        { key: 'init', text: 'void push(MinHeap *hp, int node, int dist) {', indent: 0 },
        { key: 'init', text: '    // Thêm Node mới vào đống và sủi bọt vun đống (Up-heap) O(log V)', indent: 1 },
        { key: 'init', text: '}', indent: 0 },
        { key: 'init', text: 'HeapNode pop(MinHeap *hp) {', indent: 0 },
        { key: 'init', text: '    // Trích xuất phần tử cực tiểu và vun đống lại (Down-heap) O(log V)', indent: 1 },
        { key: 'init', text: '}', indent: 0 },
        { key: 'init', text: '', indent: 0 },
        { key: 'init', text: 'void Dijkstra_PQ(int graph[100][100], int n, int src)', indent: 0 },
        { key: 'init', text: '{', indent: 0 },
        { key: 'init', text: '    for (int i = 0; i < n; i++) {', indent: 1 },
        { key: 'init', text: '        dist[i] = INF;', indent: 2 },
        { key: 'init', text: '        prev[i] = -1;', indent: 2 },
        { key: 'init', text: '    }', indent: 1 },
        { key: 'init', text: '    dist[src] = 0;', indent: 1 },
        { key: 'init', text: '    MinHeap hp = { .size = 0 };', indent: 1 },
        { key: 'init', text: '    push(&hp, src, 0); // nạp nguồn vào heap', indent: 1 },
        { key: 'init', text: '', indent: 0 },
        { key: 'loop_start', text: '    while (hp.size > 0)', indent: 1 },
        { key: 'loop_start', text: '    {', indent: 1 },
        { key: 'extract_min', text: '        HeapNode current = pop(&hp); // Lấy cực tiểu u, O(log V)', indent: 2 },
        { key: 'extract_min', text: '        int u = current.node;', indent: 2 },
        { key: 'extract_min', text: '        if (current.dist > dist[u]) continue;', indent: 2 },
        { key: 'extract_min', text: '', indent: 0 },
        { key: 'neighbor_loop', text: '        for (int v = 0; v < n; v++)', indent: 2 },
        { key: 'neighbor_loop', text: '        {', indent: 2 },
        { key: 'relaxation_check', text: '            if (graph[u][v] > 0)', indent: 3 },
        { key: 'relaxation_check', text: '            {', indent: 3 },
        { key: 'relaxation_check', text: '                int w = graph[u][v];', indent: 4 },
        { key: 'relaxation_check', text: '                if (dist[u] + w < dist[v])', indent: 4 },
        { key: 'relaxation_check', text: '                {', indent: 4 },
        { key: 'relaxation_action', text: '                    dist[v] = dist[u] + w;', indent: 5 },
        { key: 'relaxation_action', text: '                    prev[v] = u;', indent: 5 },
        { key: 'relaxation_action', text: '                    push(&hp, v, dist[v]); // Đẩy vào Heap, O(log V)', indent: 5 },
        { key: 'relaxation_action', text: '                }', indent: 4 },
        { key: 'relaxation_check', text: '            }', indent: 3 },
        { key: 'neighbor_loop', text: '        }', indent: 2 },
        { key: 'loop_start', text: '    }', indent: 1 },
        { key: 'done', text: '}', indent: 0 },
      ]
    }
  }
};
