import { CodeLine, CodeLanguage } from '../types';

export const codeTemplates: Record<CodeLanguage, { title: string; lines: CodeLine[] }> = {
  'pseudo-c': {
    title: 'Ngôn Ngữ Tựa C (Pseudocode)',
    lines: [
      { key: 'init', text: 'function dijkstra(Graph G, Node start, Node end):', indent: 0 },
      { key: 'init', text: '    dist = array of size G.V filled with INFINITY', indent: 0 },
      { key: 'init', text: '    prev = array of size G.V filled with NULL', indent: 0 },
      { key: 'init', text: '    dist[start] = 0', indent: 0 },
      { key: 'init', text: '    Q = priority queue containing all nodes with dist', indent: 0 },
      { key: 'loop_start', text: '    while Q is not empty:', indent: 0 },
      { key: 'extract_min', text: '        u = Q.extract_min()', indent: 1 },
      { key: 'check_destination', text: '        if u == end:', indent: 1 },
      { key: 'check_destination', text: '            break  // Reached destination', indent: 2 },
      { key: 'mark_visited', text: '        u.visited = true', indent: 1 },
      { key: 'neighbor_loop', text: '        for each unvisited neighbor v of u:', indent: 1 },
      { key: 'relaxation_check', text: '            alt = dist[u] + weight(u, v)', indent: 2 },
      { key: 'relaxation_check', text: '            if alt < dist[v]:', indent: 2 },
      { key: 'relaxation_action', text: '                dist[v] = alt', indent: 3 },
      { key: 'relaxation_action', text: '                prev[v] = u', indent: 3 },
      { key: 'relaxation_action', text: '                Q.decrease_priority(v, alt)', indent: 3 },
      { key: 'done', text: '    return dist, prev', indent: 0 },
    ],
  },
  'cpp': {
    title: 'C++',
    lines: [
      { key: 'init', text: 'void dijkstra(const vector<vector<pair<int, int>>>& adj, int start, int end) {', indent: 0 },
      { key: 'init', text: '    vector<int> dist(adj.size(), INF);', indent: 1 },
      { key: 'init', text: '    vector<int> prev(adj.size(), -1);', indent: 1 },
      { key: 'init', text: '    priority_queue<pair<int, int>, vector<pair<int, int>>, greater<pair<int, int>>> pq;', indent: 1 },
      { key: 'init', text: '    dist[start] = 0;', indent: 1 },
      { key: 'init', text: '    pq.push({0, start});', indent: 1 },
      { key: 'loop_start', text: '    while (!pq.empty()) {', indent: 1 },
      { key: 'extract_min', text: '        auto [d, u] = pq.top(); pq.pop();', indent: 2 },
      { key: 'extract_min', text: '        if (d > dist[u]) continue;', indent: 2 },
      { key: 'check_destination', text: '        if (u == end) break;', indent: 2 },
      { key: 'mark_visited', text: '        // Mark u as visited (implicit in pq optimization)', indent: 2 },
      { key: 'neighbor_loop', text: '        for (auto& edge : adj[u]) {', indent: 2 },
      { key: 'neighbor_loop', text: '            int v = edge.first, weight = edge.second;', indent: 3 },
      { key: 'relaxation_check', text: '            if (dist[u] + weight < dist[v]) {', indent: 3 },
      { key: 'relaxation_action', text: '                dist[v] = dist[u] + weight;', indent: 4 },
      { key: 'relaxation_action', text: '                prev[v] = u;', indent: 4 },
      { key: 'relaxation_action', text: '                pq.push({dist[v], v});', indent: 4 },
      { key: 'relaxation_action', text: '            }', indent: 3 },
      { key: 'neighbor_loop', text: '        }', indent: 2 },
      { key: 'loop_start', text: '    }', indent: 1 },
      { key: 'done', text: '}', indent: 0 },
    ],
  },
  'python': {
    title: 'Python',
    lines: [
      { key: 'init', text: 'import heapq', indent: 0 },
      { key: 'init', text: 'def dijkstra(graph, start, end):', indent: 0 },
      { key: 'init', text: '    dist = {node: float("inf") for node in graph}', indent: 1 },
      { key: 'init', text: '    prev = {node: None for node in graph}', indent: 1 },
      { key: 'init', text: '    dist[start] = 0', indent: 1 },
      { key: 'init', text: '    pq = [(0, start)]', indent: 1 },
      { key: 'loop_start', text: '    while pq:', indent: 1 },
      { key: 'extract_min', text: '        d, u = heapq.heappop(pq)', indent: 2 },
      { key: 'extract_min', text: '        if d > dist[u]: continue', indent: 2 },
      { key: 'check_destination', text: '        if u == end: break', indent: 2 },
      { key: 'neighbor_loop', text: '        for v, weight in graph[u].items():', indent: 2 },
      { key: 'relaxation_check', text: '            alt = dist[u] + weight', indent: 3 },
      { key: 'relaxation_check', text: '            if alt < dist[v]:', indent: 3 },
      { key: 'relaxation_action', text: '                dist[v] = alt', indent: 4 },
      { key: 'relaxation_action', text: '                prev[v] = u', indent: 4 },
      { key: 'relaxation_action', text: '                heapq.heappush(pq, (alt, v))', indent: 4 },
      { key: 'done', text: '    return dist, prev', indent: 1 },
    ],
  },
  'javascript': {
    title: 'JavaScript',
    lines: [
      { key: 'init', text: 'function dijkstra(graph, start, end) {', indent: 0 },
      { key: 'init', text: '    const dist = {};', indent: 1 },
      { key: 'init', text: '    const prev = {};', indent: 1 },
      { key: 'init', text: '    const selectQueue = [];', indent: 1 },
      { key: 'init', text: '    for (let node in graph) {', indent: 1 },
      { key: 'init', text: '        dist[node] = (node === start) ? 0 : Infinity;', indent: 2 },
      { key: 'init', text: '        prev[node] = null;', indent: 2 },
      { key: 'init', text: '        selectQueue.push(node);', indent: 2 },
      { key: 'init', text: '    }', indent: 1 },
      { key: 'loop_start', text: '    while (selectQueue.length > 0) {', indent: 1 },
      { key: 'extract_min', text: '        selectQueue.sort((a, b) => dist[a] - dist[b]);', indent: 2 },
      { key: 'extract_min', text: '        const u = selectQueue.shift();', indent: 2 },
      { key: 'extract_min', text: '        if (dist[u] === Infinity) break;', indent: 2 },
      { key: 'check_destination', text: '        if (u === end) break;', indent: 2 },
      { key: 'neighbor_loop', text: '        for (let v in graph[u]) {', indent: 2 },
      { key: 'relaxation_check', text: '            let alt = dist[u] + graph[u][v];', indent: 3 },
      { key: 'relaxation_check', text: '            if (alt < dist[v]) {', indent: 3 },
      { key: 'relaxation_action', text: '                dist[v] = alt;', indent: 4 },
      { key: 'relaxation_action', text: '                prev[v] = u;', indent: 4 },
      { key: 'relaxation_action', text: '            }', indent: 3 },
      { key: 'neighbor_loop', text: '        }', indent: 2 },
      { key: 'loop_start', text: '    }', indent: 1 },
      { key: 'done', text: '    return { dist, prev };', indent: 1 },
      { key: 'done', text: '}', indent: 0 },
    ],
  },
};
